import React, { useState } from 'react';
import { User } from '../types';
import { api } from '../services/api';
import { X, Lock, KeyRound, ShieldAlert, UserCheck, ArrowRight, ShieldCheck, QrCode } from 'lucide-react';

interface AuthModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLoginSuccess: (user: User) => void;
}

export const AuthModal: React.FC<AuthModalProps> = ({
  isOpen,
  onClose,
  onLoginSuccess
}) => {
  if (!isOpen) return null;

  const [mode, setMode] = useState<'login' | 'register' | 'mfa'>('login');
  const [email, setEmail] = useState('admin@nexus.io');
  const [name, setName] = useState('Alexandra Vance');
  const [mfaCode, setMfaCode] = useState('839201');
  const [errorMsg, setErrorMsg] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLoginSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');

    try {
      const res = await api.login(email);
      if (res.requiresMfa) {
        setMode('mfa');
      } else if (res.user) {
        onLoginSuccess(res.user);
        onClose();
      }
    } catch (err: any) {
      setErrorMsg(err.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  const handleMfaVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');

    try {
      const res = await api.verifyMfa(email, mfaCode);
      if (res.success && res.user) {
        onLoginSuccess(res.user);
        onClose();
      }
    } catch (err: any) {
      setErrorMsg(err.message || 'Invalid MFA Code');
    } finally {
      setLoading(false);
    }
  };

  const handleRegisterSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');

    try {
      const res = await api.register(name, email, 'customer');
      onLoginSuccess(res.user);
      onClose();
    } catch (err: any) {
      setErrorMsg(err.message || 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  const handleQuickLogin = (roleEmail: string) => {
    setEmail(roleEmail);
    if (roleEmail === 'admin@nexus.io') {
      setMode('mfa');
    } else {
      api.login(roleEmail).then(res => {
        if (res.user) {
          onLoginSuccess(res.user);
          onClose();
        }
      });
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/75 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl overflow-hidden p-6 text-xs">

        {/* Close Button */}
        <button onClick={onClose} className="absolute top-4 right-4 p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-lg">
          <X className="w-5 h-5" />
        </button>

        {errorMsg && (
          <div className="mb-4 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* MFA STEP */}
        {mode === 'mfa' ? (
          <form onSubmit={handleMfaVerify} className="space-y-4 text-center">
            <div className="w-12 h-12 mx-auto rounded-xl bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
              <Lock className="w-6 h-6" />
            </div>

            <div>
              <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
                Multi-Factor Authentication Required
              </h3>
              <p className="text-slate-500 mt-1">
                Enter the 6-digit OTP code sent to <strong className="text-slate-800 dark:text-slate-200">{email}</strong> or generated by your Authenticator app.
              </p>
            </div>

            {/* Simulated Authenticator Card */}
            <div className="p-3 bg-slate-50 dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700 flex items-center gap-3 text-left">
              <QrCode className="w-8 h-8 text-indigo-500 shrink-0" />
              <div>
                <span className="font-semibold text-slate-900 dark:text-slate-100 block">NEXUS Security Key</span>
                <span className="text-[10px] text-slate-400 font-mono">OTP: 839201 (pre-filled for demo)</span>
              </div>
            </div>

            <div>
              <input
                type="text"
                required
                maxLength={6}
                value={mfaCode}
                onChange={(e) => setMfaCode(e.target.value)}
                placeholder="839201"
                className="w-full text-center py-3 text-lg font-mono font-bold tracking-widest rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-indigo-500/50"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl shadow-lg shadow-indigo-600/20 transition-all flex items-center justify-center gap-2"
            >
              <ShieldCheck className="w-4 h-4" />
              <span>{loading ? 'Verifying MFA...' : 'Verify & Log In'}</span>
            </button>

            <button
              type="button"
              onClick={() => setMode('login')}
              className="text-slate-400 hover:underline block mx-auto text-[11px]"
            >
              &larr; Switch Account
            </button>
          </form>
        ) : mode === 'login' ? (
          /* LOGIN FORM */
          <form onSubmit={handleLoginSubmit} className="space-y-4">
            <div className="text-center">
              <h3 className="text-base font-extrabold text-slate-900 dark:text-slate-100">
                Sign In to NEXUS Store
              </h3>
              <p className="text-slate-500 mt-1">Sign in to sync your guest cart and track orders.</p>
            </div>

            <div>
              <label className="block text-slate-500 mb-1 font-semibold">Email Address</label>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="admin@nexus.io"
                className="w-full p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-100"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl shadow-md transition-all flex items-center justify-center gap-2"
            >
              <span>Continue</span>
              <ArrowRight className="w-4 h-4" />
            </button>

            {/* Quick Demo Login Shortcut Buttons */}
            <div className="pt-3 border-t border-slate-100 dark:border-slate-800 space-y-2">
              <span className="block text-[10px] uppercase font-bold text-slate-400 text-center tracking-wider">
                Demo Quick Authentication Roles
              </span>
              <div className="grid grid-cols-3 gap-2">
                <button
                  type="button"
                  onClick={() => handleQuickLogin('admin@nexus.io')}
                  className="p-2 rounded-lg bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 font-bold hover:bg-indigo-100 transition-colors text-[10px]"
                >
                  Admin (MFA)
                </button>
                <button
                  type="button"
                  onClick={() => handleQuickLogin('manager@nexus.io')}
                  className="p-2 rounded-lg bg-cyan-50 dark:bg-cyan-950/60 border border-cyan-200 dark:border-cyan-800 text-cyan-700 dark:text-cyan-300 font-bold hover:bg-cyan-100 transition-colors text-[10px]"
                >
                  Manager
                </button>
                <button
                  type="button"
                  onClick={() => handleQuickLogin('sarah.j@example.com')}
                  className="p-2 rounded-lg bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 font-bold hover:bg-slate-200 transition-colors text-[10px]"
                >
                  Customer
                </button>
              </div>
            </div>

            <div className="text-center pt-2">
              <span className="text-slate-500">Don't have an account? </span>
              <button
                type="button"
                onClick={() => setMode('register')}
                className="font-bold text-indigo-600 dark:text-indigo-400 hover:underline"
              >
                Create One
              </button>
            </div>
          </form>
        ) : (
          /* REGISTER FORM */
          <form onSubmit={handleRegisterSubmit} className="space-y-4">
            <div className="text-center">
              <h3 className="text-base font-extrabold text-slate-900 dark:text-slate-100">
                Create Customer Account
              </h3>
              <p className="text-slate-500 mt-1">Join NEXUS for persistent shopping & order history.</p>
            </div>

            <div>
              <label className="block text-slate-500 mb-1 font-semibold">Full Name</label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Jane Doe"
                className="w-full p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-100"
              />
            </div>

            <div>
              <label className="block text-slate-500 mb-1 font-semibold">Email Address</label>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="jane@example.com"
                className="w-full p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-100"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl shadow-md transition-all"
            >
              Register & Sync Cart
            </button>

            <div className="text-center pt-2">
              <span className="text-slate-500">Already registered? </span>
              <button
                type="button"
                onClick={() => setMode('login')}
                className="font-bold text-indigo-600 dark:text-indigo-400 hover:underline"
              >
                Sign In
              </button>
            </div>
          </form>
        )}

      </div>
    </div>
  );
};
